# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          repository: 'ElangoRajendran/my-docs-test'
          ref: 'master'
          path: ug_spellchecker          
            
      - uses: actions/checkout@v2
        with:
          path: Spell-Checker     

          
      - run: echo $pwd
      - run: echo process.env.GITHUB_REF
        
      - run: ls
      
      - run: ls
        working-directory: ./ug_spellchecker
        
      - run: ls
        working-directory: ./Spell-Checker
      
      - uses: juliangruber/find-pull-request-action@v1
        id: PR
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         filterOutClosed: true       
      - run: echo "Your PR is ${prNumber} and its JSON is ${prJSON}"
        if: success() && steps.PR.outputs.number
        env:
         prNumber: ${{ steps.PR.outputs.number }}
         prJSON: ${{ steps.PR.outputs.pr }}
        
        
      - run: powershell .\build.ps1
        working-directory: ./ug_spellchecker


      - run: ls
      
      - run: ls
        working-directory: ./ug_spellchecker
        
      - run: ls
        working-directory: ./Spell-Checker
