# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          repository: 'ElangoRajendran/my-docs-test'
          ref: 'master'
          path: ug_spellchecker          
            
      - uses: actions/checkout@v2
        with:
          path: Spell-Checker     
         
      - name: branchCommitDetails 
        run: curl -X GET -u ElangoRajendran:6e8def9c9e437c576e9896d345059560e1932c2d https://api.github.com/repos/ElangoRajendran/my-docs/pulls/${{ github.event.number }}/files| grep -w filename
        

      - run: powershell .\build.ps1
        working-directory: ./ug_spellchecker
