# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          repository: 'Siddharth/Test-Project-1'
          ref: 'master'
          path: Project-1
                                  
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: Project-2
      
      - run: powershell .\build.ps1 -Target build -Targetbranch ${{ github.base_ref }} -Branch ${{ github.head_ref }} 
        working-directory: ./Project-1
